import LegalLayout, { Section, P, UL, LI, Highlight, LegalLink } from '../components/LegalLayout'

export default function Disclaimer() {
  return (
    <LegalLayout title="Disclaimer" badge="Legal" updated="April 2026">

      <Section title="1. No Financial Advice">
        <P>Apex Decision Engine ("ADE") is a market intelligence and analysis platform. <strong style={{ color: 'rgba(255,255,255,0.85)' }}>Nothing on this platform constitutes financial, investment, tax, or legal advice.</strong> All content — including signals, scores, PRISM analysis, CIPHER agent briefs, UOA data, charts, screener results, and any other outputs — is provided for <strong style={{ color: 'rgba(255,255,255,0.85)' }}>informational and educational purposes only.</strong></P>
        <P>ADE is not a registered investment adviser, broker-dealer, financial planner, or commodity trading adviser under the Investment Advisers Act of 1940, the Securities Exchange Act of 1934, or any other applicable law or regulation.</P>
      </Section>

      <Section title="2. Not a Recommendation">
        <P>No output from ADE — including BUY, AVOID, or WATCH verdicts from the PRISM signal engine — should be construed as a recommendation or solicitation to buy, sell, or hold any security or financial instrument. Signals are the output of algorithmic models applied to historical and real-time data; they carry no guarantee of accuracy, completeness, or profitability.</P>
        <P>CIPHER, the APEX-tier AI agent, provides personalized market briefings based on your preferences. These briefs are generated by a large language model (Anthropic Claude) and are explicitly <strong style={{ color: 'rgba(255,255,255,0.85)' }}>not investment advice</strong> from a human advisor.</P>
      </Section>

      <Section title="3. User Responsibility">
        <P>You are solely responsible for all trading and investment decisions you make based on or in connection with information obtained from ADE. You should:</P>
        <UL>
          <LI>Conduct your own independent research and due diligence</LI>
          <LI>Consult a qualified, licensed financial professional before acting on any information</LI>
          <LI>Understand and accept the full risks involved — see our <LegalLink to="/risk-disclosure">Risk Disclosure</LegalLink></LI>
          <LI>Apply your own position sizing, stop-loss, and risk management rules</LI>
          <LI>Never invest more than you can afford to lose</LI>
        </UL>
      </Section>

      <Section title="4. AI Limitations">
        <P>AI-generated content on this platform (PRISM signals, CIPHER briefs, chat responses) is produced by machine learning models that:</P>
        <UL>
          <LI>Can be incorrect, biased, or incomplete</LI>
          <LI>Are not updated in real time and may not reflect the latest market conditions</LI>
          <LI>Do not have access to all market information or order flow data</LI>
          <LI>Should never be treated as the sole basis for a financial decision</LI>
        </UL>
        <P><Highlight>CIPHER</Highlight> and <Highlight>PRISM</Highlight> are marketing names for AI systems. They are not human advisors, employees, or registered professionals.</P>
      </Section>

      <Section title="5. Third-Party Data">
        <P>Market data, prices, and financial information displayed on ADE may be sourced from third parties (Yahoo Finance, Finnhub, and others). ADE does not guarantee the accuracy, timeliness, or completeness of this data. Prices shown are indicative only and may differ from live exchange data or your broker's quoted prices.</P>
      </Section>

      <Section title="6. Track Record Data">
        <P>Signal accuracy metrics and track record data displayed on ADE represent historical outcomes of AI-generated signals under simulated conditions. These figures:</P>
        <UL>
          <LI>Do not account for real-world execution costs (commissions, slippage, bid-ask spreads)</LI>
          <LI>Are based on end-of-day or delayed price data and may not reflect actual entry/exit prices</LI>
          <LI>Are not audited by any third party</LI>
          <LI>Do not guarantee similar future performance</LI>
        </UL>
      </Section>

      <Section title="7. Governing Documents">
        <P>This Disclaimer is part of a set of legal documents that govern your use of ADE. Please also review our <LegalLink to="/terms">Terms of Service</LegalLink>, <LegalLink to="/privacy">Privacy Policy</LegalLink>, and <LegalLink to="/risk-disclosure">Risk Disclosure</LegalLink>. For questions, contact <Highlight>support@apexdecisionengine.com</Highlight>.</P>
      </Section>

    </LegalLayout>
  )
}
