import LegalLayout, { Section, P, UL, LI, Highlight, LegalLink } from '../components/LegalLayout'

export default function RiskDisclosure() {
  return (
    <LegalLayout title="Risk Disclosure" badge="Legal" updated="April 2026">

      <Section title="1. General Investment Risk">
        <P>Trading and investing in financial markets involves substantial risk of loss. The value of securities, options, futures, and other financial instruments can fall as well as rise. You may lose some or all of your invested capital. <strong style={{ color: 'rgba(255,255,255,0.85)' }}>Past performance is not indicative of future results.</strong></P>
        <P>Before trading or investing, carefully consider your investment objectives, financial situation, experience level, and risk tolerance. Only trade with capital you can afford to lose.</P>
      </Section>

      <Section title="2. Options and Derivatives Risk">
        <P>Options, futures, and other derivative instruments carry a high degree of risk and are not suitable for all investors. Specific risks include:</P>
        <UL>
          <LI><strong style={{ color: 'rgba(255,255,255,0.75)' }}>Leverage risk</strong> — options can amplify both gains and losses; losses may exceed your initial premium paid</LI>
          <LI><strong style={{ color: 'rgba(255,255,255,0.75)' }}>Time decay (theta)</strong> — options lose value as expiration approaches regardless of underlying price movement</LI>
          <LI><strong style={{ color: 'rgba(255,255,255,0.75)' }}>Volatility risk</strong> — changes in implied volatility can adversely affect option prices independent of direction</LI>
          <LI><strong style={{ color: 'rgba(255,255,255,0.75)' }}>Liquidity risk</strong> — some options may have wide bid-ask spreads or low open interest, making it difficult to exit positions at favorable prices</LI>
          <LI><strong style={{ color: 'rgba(255,255,255,0.75)' }}>Assignment risk</strong> — short options positions may be assigned at any time prior to expiration</LI>
          <LI><strong style={{ color: 'rgba(255,255,255,0.75)' }}>Expiration risk</strong> — options expire worthless if they are out-of-the-money at expiration</LI>
        </UL>
      </Section>

      <Section title="3. AI Signal Risk">
        <P>PRISM signals and CIPHER briefs are generated by algorithmic models and large language models (Anthropic Claude). These systems:</P>
        <UL>
          <LI>Are trained on historical data and cannot predict future market conditions</LI>
          <LI>May produce incorrect, incomplete, or delayed analysis</LI>
          <LI>Do not account for all market variables, breaking news, or macro regime shifts</LI>
          <LI>Have no legal obligation to be accurate or profitable</LI>
          <LI>Are not reviewed by licensed financial analysts before delivery</LI>
        </UL>
        <P>ADE signals should be treated as <strong style={{ color: 'rgba(255,255,255,0.85)' }}>one analytical input among many</strong> — not as trading instructions. Signal accuracy metrics displayed on the Track Record page reflect historical outcomes only and do not guarantee future performance.</P>
      </Section>

      <Section title="4. Market Risk Factors">
        <P>Financial markets can be affected by numerous unpredictable factors including but not limited to:</P>
        <UL>
          <LI>Macroeconomic data releases (CPI, NFP, GDP, Fed decisions)</LI>
          <LI>Geopolitical events, wars, and sanctions</LI>
          <LI>Corporate earnings surprises, guidance changes, and management actions</LI>
          <LI>Regulatory changes and SEC/CFTC enforcement actions</LI>
          <LI>Market structure events: flash crashes, trading halts, exchange outages</LI>
          <LI>Liquidity crises, short squeezes, and gamma squeezes</LI>
          <LI>Black swan events and tail risks not captured by historical models</LI>
        </UL>
      </Section>

      <Section title="5. Unusual Options Activity (UOA) Risk">
        <P>UOA data displayed by ADE identifies large or unusual options flows. This data:</P>
        <UL>
          <LI>May reflect hedging activity, institutional positioning, or automated strategies — not necessarily bullish/bearish directional bets</LI>
          <LI>Does not confirm insider knowledge, leaked information, or guaranteed outcomes</LI>
          <LI>Is delayed from real-time by data provider latency</LI>
          <LI>Should not be followed blindly without independent analysis</LI>
        </UL>
      </Section>

      <Section title="6. Execution and Broker Risk">
        <P>ADE does not execute trades, manage portfolios, or have custody of any assets. All execution risk lies between you and your broker. Risks include:</P>
        <UL>
          <LI>Slippage between the price shown in ADE and your actual fill price</LI>
          <LI>Broker outages or system failures during fast markets</LI>
          <LI>Margin calls and forced liquidation if positions move against you</LI>
          <LI>Regulatory restrictions on certain instruments depending on your account type and jurisdiction</LI>
        </UL>
        <P>Ensure you understand your broker's margin requirements, options approval levels, and trading hours before acting on any signal.</P>
      </Section>

      <Section title="7. No Guarantee">
        <P>ADE makes no representation or warranty that any signal, score, recommendation, or analysis will be accurate, complete, timely, or result in a profit. You assume all responsibility for your trading decisions. We strongly recommend consulting a qualified, licensed financial professional before making any investment decision.</P>
        <P>See also our <LegalLink to="/disclaimer">Disclaimer</LegalLink> and <LegalLink to="/terms">Terms of Service</LegalLink>.</P>
      </Section>

    </LegalLayout>
  )
}
